### ISSUE TITLE
[Suggestion] Make this multi-user-capable

### ISSUE THREAD

**Issue by Dracon23** [earshel/PokeyPyManager#11]
I've been asked by my sons if I could set them up with an installation of this on our LAN.

I'll be taking the code for a spin (forked it a few mins ago) and see if I can make this multi-user-capable. The main issue here will be using proxyfication at some point though, seeing as niantic definitely drops the ban hammer. If I can get this working nicely and you want me to I can contribute a PR.

**Comment by earshel** [comment]
You're not the first person who's expressed interest in this - so please do take a look at making it happen. I haven't had an opportunity to work on it yet. Let me know what you come up with ;)
