### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by FacuM** [earshel/PokeyPyManager#13]
![image](https://cloud.githubusercontent.com/assets/3741108/17654752/ce886518-627c-11e6-9453-71664fe13db3.png)

This is the error I get when I try to build it and install requirements.

**Comment by earshel** [comment]
You may have to install this first: https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by FacuM** [comment]
Thanks @earshel I'll give it a try.

**Comment by earshel** [comment]
No problemo!

**Comment by FacuM** [comment]
Thank you so much. It worked, but my account was already banned, haha.
