### ISSUE TITLE
Type Error?

### ISSUE THREAD

**Issue by paul30001** [earshel/PokeyPyManager#4]
What is this? 
Python and pip are installed properly, I'm using a bunch of scanners, so idk what it can be. 

![screenshot 44](https://cloud.githubusercontent.com/assets/20823132/17585815/d8593da4-5f72-11e6-82f4-8e3c86b4cd37.png)

**Comment by earshel** [comment]
Did you run this command in the root directory of the repo?

> pip install -r requirements.txt

**Comment by paul30001** [comment]
Yup, where I extracted it, Installed successfully. :'(

![screenshot 45](https://cloud.githubusercontent.com/assets/20823132/17601568/aadb1d84-5fbd-11e6-8989-8b8c6db3c279.png)

**Comment by earshel** [comment]
Hmph. I haven't been able to make this happen on my end. Are you using Python 2.7?

**Comment by paul30001** [comment]
@earshel First screenshot is me trying to improvise, but didn't work.

The other 2 are me installing another instance in virtualenv, and as you can see - same issue! :( 
![screenshot 46](https://cloud.githubusercontent.com/assets/20823132/17602046/b71ed840-5fbf-11e6-81c0-7745a6fe1504.png)
![screenshot 47](https://cloud.githubusercontent.com/assets/20823132/17602045/b71e4466-5fbf-11e6-94e2-d04acbabb3ab.png)
![screenshot 48](https://cloud.githubusercontent.com/assets/20823132/17602047/b72553be-5fbf-11e6-8230-abf7db562b6d.png)

**Comment by paul30001** [comment]
@earshel Sorry I had the last reply typed up, but didn't click Comment.

And no, I'm using the latest version of Python.

**Comment by earshel** [comment]
I think that's the issue - I've only tested this on 2.7, and I've heard from others that it doesn't work properly with Python 3. I'm not sure how to solve this unless you can revert to 2.7.

**Comment by paul30001** [comment]
Are you planning on moving it to Python 3? It's more stable?

**Comment by earshel** [comment]
I have no plans to do this. Everything i know about Python, I've learned since Pokemon Go's release. I have no idea where to start, but if you are capable of doing this, I'm not opposed to moving to 3.0.

**Comment by paul30001** [comment]
Haha, I know nothing about Python, but your statement is actually inspiring, I'll try to learn Python now, and maybe in few weeks come up with another useful tool xp

**Comment by paul30001** [comment]
Haha, I know nothing about Python, but your statement is actually inspiring, I'll try to learn Python now, and maybe in few weeks come up with another useful tool xp
