### ISSUE TITLE
Socket Error?

### ISSUE THREAD

**Issue by MaxGriswald** [earshel/PokeyPyManager#7]
![socketerror](https://cloud.githubusercontent.com/assets/20977887/17603735/957d60dc-5fe0-11e6-8683-d41c2c6e03bc.jpg)

No real idea on this one...

**Comment by earshel** [comment]
Are you running a firewall that might be causing this? Is port 5100 in use by another program? Perhaps edit mgr.py line 344 to say 127.0.0.1 instead of 0.0.0.0?

**Comment by DNA64** [comment]
> root@pogo:~/PokeyPyManager# ./compile.sh
> ./compile.sh: line 4: cd: ./proto/: No such file or directory
> ./compile.sh: line 5: ./compile.py: No such file or directory

`#!/bin/bash

rm -rf pogo/proto
cd ./proto/
./compile.py -l python -o ../pogo/
cd ../
`

**Comment by MaxGriswald** [comment]
Changed to 127.0.0.1 and it works great.  It seems to break every time I do a mass-event, like transferring, though, and I have to restart the process.  Not a big issue at all though.

**Comment by earshel** [comment]
I just made a huge commit with the most up-to-date API and Protos. Please check out the new version. If this is still an issue, please let me know.
