### ISSUE TITLE
[Suggestion] Don't keep connection alive.

### ISSUE THREAD

**Issue by Dracon23** [earshel/PokeyPyManager#8]
I've been using this for a few hours, and have grown to dislike the keep-alive behavior. After twenty minutes the heartbeats fail. 

A suggestion: Have the user request a refresh of the data and only then login and request the data.

**Comment by earshel** [comment]
I upgraded to the newest commit of the API I use and also upgraded to the most recent PROTOS. I removed the heartbeat altogether. Please check out the newest version and let me know if this works better for you. Thanks :)

**Comment by Dracon23** [comment]
Hm, bit awkward, but it seems I seem to be missing something vital here...

I just raked in the newest version via pull... but the heart beat is still being sent.

**Comment by earshel** [comment]
Odd. The new commit has a completely different directory structure. Are you running mgr.py from the root directory now, rather than from the /pogo/ directory? I just cloned the repo and it's not sending the heartbeat on my end.

**Comment by Dracon23** [comment]
ack, no, that should explain that :d

This is one of my typical layer 8 errors...

Lemme check then.

**Comment by earshel** [comment]
I'd recommend starting over by cloning a fresh copy of the repo to be safe, so you don't end up with duplicate files.

**Comment by Dracon23** [comment]
Did so.... Looks nice so far

**Comment by Dracon23** [comment]
So, gave this a spin and it looks okay... something else cropped up though, opened up a new suggestion.
