### ISSUE TITLE
[Bug] Cannot select pokémon

### ISSUE THREAD

**Issue by Dracon23** [earshel/PokeyPyManager#9]
Server OS - Ubuntu 16.04 - x64
Python 2.7.12
Latest git commit (0472a3b789a1afdced63cfbd1136fc5d698971f4)
Accessed via chrome on win10, happens on firefox and mobile chrome as well...

Description - 

For the life of me, I cannot select pokémon to interact with. no amount of clicking, doubleclicking and tabbing to and then hitting space will do anything.

**Comment by earshel** [comment]
I can't reproduce this. In order to select a Pokemon, click on the photo of the Pokemon. It works in Chrome and Firefox in Windows 10 for me. In Chrome, perhaps hit f12 and then click on the Console, and try selecting a Pokemon. Is it throwing any errors?

**Comment by Dracon23** [comment]
Fresh Clone has it working again
